version: "3.9"
services:
  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_DB: "job"
      POSTGRES_USER: "job_user"
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
