version: "3.9"
services:
  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_DB: "job"
      POSTGRES_USER: "job_user"
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: DEV_ACCESS_KEY
      MINIO_SECRET_KEY: DEV_SECRET_KEY
    command: server --address 0.0.0.0:9000 --console-address "0.0.0.0:9001" /data

