name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
      - services/api
  pull_request:

jobs:
  build-api:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: services/api
      - run: npm run build --if-present
        working-directory: services/api
      - run: npm test
        working-directory: services/api
      - run: npm run lint
        working-directory: services/api
      - run: npm run prettier
        working-directory: services/api
